from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class PlannerResult:
    provider: str
    model: str
    plan: dict[str, Any]
    raw_response: str = ""


class DeterministicPlanner:
    """Offline fallback planner for smoke tests and disconnected appliances."""

    model = "deterministic-local-planner"

    def generate_plan(
        self,
        task: str,
        evidence: list[dict[str, Any]] | None = None,
        requested_action_boundary: str = "T0",
    ) -> PlannerResult:
        evidence = evidence or []
        confidence = "Medium" if evidence else "Low"
        missing = [] if evidence else ["Operator evidence or read-only diagnostic output"]
        validation = [
            "Collect timestamped read-only diagnostics before any change.",
            "Re-run the same read-only check after any approved action.",
        ]
        rollback = [] if requested_action_boundary == "T0" else [
            "Return to the last known-good configuration or stop before execution."
        ]

        plan = {
            "summary": f"Governed plan draft for: {task}",
            "known": [item.get("summary") or item.get("source", "") for item in evidence],
            "missing": missing,
            "required": missing or ["Confirm evidence freshness and environment scope"],
            "domains": _infer_domains(task),
            "risk_tier": requested_action_boundary,
            "confidence": confidence,
            "recommended_actions": [
                {
                    "description": "Collect and attach read-only evidence for the reported condition.",
                    "risk_tier": "T0",
                    "requires_approval": False,
                }
            ],
            "validation": validation,
            "rollback": rollback,
            "governance": {
                "direct_impact": requested_action_boundary != "T0",
                "notes": [
                    "Generated by deterministic offline planner because no local LLM runtime responded."
                ],
            },
        }
        return PlannerResult(provider="deterministic", model=self.model, plan=plan)


class OllamaClient:
    """Minimal Ollama-compatible adapter using only the Python standard library."""

    def __init__(
        self,
        base_url: str | None = None,
        model: str | None = None,
        timeout_seconds: float = 30.0,
    ) -> None:
        self.base_url = (base_url or os.environ.get("EOA_OLLAMA_URL") or "").rstrip("/")
        self.model = model or os.environ.get("EOA_OLLAMA_MODEL") or "llama3:8b"
        self.timeout_seconds = timeout_seconds

    def available(self) -> bool:
        return bool(self.base_url)

    def health(self) -> dict[str, object]:
        if not self.available():
            return {
                "provider": "ollama",
                "configured": False,
                "healthy": False,
                "latency_ms": None,
                "model": self.model,
                "message": "EOA_OLLAMA_URL is not configured",
            }
        start = time.perf_counter()
        try:
            with urllib.request.urlopen(f"{self.base_url}/api/tags", timeout=5) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            return {
                "provider": "ollama",
                "configured": True,
                "healthy": False,
                "latency_ms": round((time.perf_counter() - start) * 1000, 2),
                "model": self.model,
                "message": str(exc),
            }
        models = [item.get("name", "") for item in payload.get("models", [])]
        return {
            "provider": "ollama",
            "configured": True,
            "healthy": True,
            "latency_ms": round((time.perf_counter() - start) * 1000, 2),
            "model": self.model,
            "model_available": self.model in models,
            "models": models,
        }

    def generate_plan(
        self,
        system_prompt: str,
        task: str,
        evidence: list[dict[str, Any]] | None = None,
        requested_action_boundary: str = "T0",
    ) -> PlannerResult:
        if not self.available():
            raise RuntimeError("Ollama base URL is not configured")

        prompt = _build_prompt(system_prompt, task, evidence or [], requested_action_boundary)
        body = json.dumps(
            {
                "model": self.model,
                "prompt": prompt,
                "stream": False,
                "format": "json",
                "options": {"temperature": 0.1},
            }
        ).encode("utf-8")
        request = urllib.request.Request(
            f"{self.base_url}/api/generate",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except urllib.error.URLError as exc:
            raise RuntimeError(f"Ollama request failed: {exc}") from exc

        raw = payload.get("response", "")
        try:
            plan = _load_json_response(raw)
        except json.JSONDecodeError as exc:
            raise RuntimeError("Ollama response was not valid JSON") from exc

        return PlannerResult(
            provider="ollama",
            model=self.model,
            plan=plan,
            raw_response=raw,
        )


def _build_prompt(
    system_prompt: str,
    task: str,
    evidence: list[dict[str, Any]],
    requested_action_boundary: str,
) -> str:
    return (
        f"{system_prompt}\n\n"
        "Return only JSON that satisfies the Enterprise Orchestrator output contract.\n"
        f"Requested action boundary: {requested_action_boundary}\n"
        f"Task: {task}\n"
        f"Evidence: {json.dumps(evidence, sort_keys=True)}"
    )


def _load_json_response(raw: str) -> dict[str, Any]:
    try:
        value = json.loads(raw)
    except json.JSONDecodeError:
        start = raw.find("{")
        end = raw.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise
        value = json.loads(raw[start : end + 1])
    if not isinstance(value, dict):
        raise json.JSONDecodeError("response JSON must be an object", raw, 0)
    return value


def _infer_domains(task: str) -> list[str]:
    lowered = task.lower()
    domains: list[str] = []
    for keyword, domain in (
        ("dns", "network"),
        ("network", "network"),
        ("auth", "auth"),
        ("kerberos", "auth"),
        ("rhel", "rhel"),
        ("systemd", "rhel"),
        ("storage", "storage"),
        ("iops", "storage"),
        ("nutanix", "nutanix"),
        ("ahv", "nutanix"),
        ("container", "container"),
        ("docker", "container"),
    ):
        if keyword in lowered and domain not in domains:
            domains.append(domain)
    return domains or ["general"]
